services:

#------------------------------------

  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer4617
    ports:
      - 4032:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

#------------------------------------

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 4080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

#------------------------------------

  task-container:
    build: .
    container_name: task-container-go 
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

#------------------------------------

volumes:
  postgres:
  pgadmin:
  task-container: