global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: task_service
    static_configs:
      - targets: ['task-container-go:8080']